-- Public citizen transparency feature tables.
-- Run this once in the Supabase SQL Editor before using the citizen actions.

create table if not exists public.citizen_verifications (
  id bigint generated by default as identity primary key,
  project_id text not null,
  work_id text,
  citizen_email text,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  distance_meters numeric(10, 2) not null,
  verified_at timestamptz not null default now()
);

create table if not exists public.citizen_feedback (
  id bigint generated by default as identity primary key,
  project_id text not null,
  work_id text,
  citizen_email text,
  site_status text not null,
  notes text not null,
  evidence_url text,
  forensic_result jsonb,
  flag text default 'Pending Citizen Field Verification',
  created_at timestamptz not null default now()
);

alter table public.citizen_verifications enable row level security;
alter table public.citizen_feedback add column if not exists rating integer check (rating between 1 and 5);

-- Optional public ledgers used by the citizen portal. These definitions are
-- additive: existing operator schemas keep their data and gain the public-read
-- contract only when the columns are absent.
create table if not exists public.allocations (
  id uuid primary key default gen_random_uuid(),
  project_id text,
  allocated_amount numeric(20, 2),
  allocation_amount numeric(20, 2),
  budget_amount numeric(20, 2),
  limit_amount numeric(20, 2),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  project_id text,
  work_id text,
  action_taken text,
  event_type text,
  sha256_hash text,
  immutable_hash text,
  created_at timestamptz not null default now()
);

alter table public.projects add column if not exists house_type text;
alter table public.projects add column if not exists constituency_type text;
update public.projects
set house = coalesce(nullif(trim(house), ''), nullif(trim(house_type), ''), nullif(trim(constituency_type), ''))
where (house is null or trim(house) = '')
  and (house_type is not null or constituency_type is not null);

alter table public.allocations enable row level security;
alter table public.audit_logs enable row level security;
alter table public.citizen_feedback enable row level security;

drop policy if exists "public_read_allocations" on public.allocations;
create policy "public_read_allocations" on public.allocations for select to anon, authenticated using (true);
drop policy if exists "public_read_audit_logs" on public.audit_logs;
create policy "public_read_audit_logs" on public.audit_logs for select to anon, authenticated using (true);

grant select on public.allocations, public.audit_logs to anon, authenticated;

-- Realtime publication is idempotent through duplicate_object handling below.
do $$
declare
  _table text;
begin
  foreach _table in array array['allocations', 'audit_logs', 'citizen_feedback'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', _table);
    exception when duplicate_object then
      null;
    end;
  end loop;
end $$;

drop policy if exists "public_insert_citizen_verifications" on public.citizen_verifications;
create policy "public_insert_citizen_verifications"
  on public.citizen_verifications for insert to anon, authenticated with check (true);

drop policy if exists "public_read_citizen_verifications" on public.citizen_verifications;
create policy "public_read_citizen_verifications"
  on public.citizen_verifications for select to anon, authenticated using (true);

drop policy if exists "public_insert_citizen_feedback" on public.citizen_feedback;
create policy "public_insert_citizen_feedback"
  on public.citizen_feedback for insert to anon, authenticated with check (true);

drop policy if exists "public_read_citizen_feedback" on public.citizen_feedback;
create policy "public_read_citizen_feedback"
  on public.citizen_feedback for select to anon, authenticated using (true);

grant select, insert on public.citizen_verifications to anon, authenticated;
grant select, insert on public.citizen_feedback to anon, authenticated;

-- Evidence bucket. If storage policies are managed separately in your project,
-- keep this insert and add equivalent object INSERT/SELECT policies in Storage.
insert into storage.buckets (id, name, public)
values ('citizen-evidence', 'citizen-evidence', true)
on conflict (id) do nothing;

-- Public, read-only aggregate used by the Citizen Portal. The function keeps
-- financial totals server-side so the browser never downloads the full dataset.
-- `allocated_limit` is the sum of recorded sanctioned allocations when an
-- explicit allocation column is not present in the source export.
create or replace function public.get_public_citizen_summary()
returns table (
  allocated_limit numeric,
  calamity_amount numeric,
  works_recommended_count bigint,
  works_recommended_amount numeric,
  works_sanctioned_count bigint,
  works_sanctioned_amount numeric,
  works_completed_count bigint,
  works_completed_amount numeric,
  total_expenditure numeric
)
language sql
security invoker
set search_path = public
as $$
  with source_rows as (
    select
      coalesce(sanctioned_amount, spent_amount, 0)::numeric as allocation,
      coalesce(spent_amount, 0)::numeric as expenditure,
      lower(coalesce(status, '')) as status
    from public.projects
  ), allocation_rows as (
    select coalesce(allocated_amount, allocation_amount, budget_amount, limit_amount, 0)::numeric as allocation
    from public.allocations
  )
  select
    case when (select count(*) from allocation_rows) > 0
      then coalesce((select sum(allocation) from allocation_rows), 0)
      else coalesce(sum(allocation), 0)
    end,
    0::numeric,
    count(*) filter (where status ~ '(recommend|propos|submit|pending)'),
    coalesce(sum(allocation) filter (where status ~ '(recommend|propos|submit|pending)'), 0),
    count(*) filter (where status ~ '(sanction|approv|award|progress|complet|success)'),
    coalesce(sum(allocation) filter (where status ~ '(sanction|approv|award|progress|complet|success)'), 0),
    count(*) filter (where status ~ '(complet|success)'),
    coalesce(sum(expenditure) filter (where status ~ '(complet|success)'), 0),
    coalesce(sum(expenditure), 0)
  from source_rows;
$$;

grant execute on function public.get_public_citizen_summary() to anon, authenticated;

-- Full-dataset counts used by the Citizen cards. These are aggregate queries,
-- not first-page browser counts, so 1,000-row PostgREST limits cannot distort
-- the public dashboard.
create or replace function public.get_public_citizen_breakdown()
returns table (
  lok_sabha_works bigint,
  lok_sabha_allocation numeric,
  rajya_sabha_works bigint,
  rajya_sabha_allocation numeric,
  high_risk_works bigint,
  moderate_risk_works bigint,
  low_risk_works bigint
)
language sql
security invoker
set search_path = public
as $$
  select
    count(*) filter (where lower(coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, ''), '')) like '%lok%' or coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, '')) = '2'),
    coalesce(sum(coalesce(sanctioned_amount, spent_amount, 0)) filter (where lower(coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, ''), '')) like '%lok%' or coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, '')) = '2'), 0),
    count(*) filter (where lower(coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, ''), '')) like '%rajya%' or coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, '')) = '1'),
    coalesce(sum(coalesce(sanctioned_amount, spent_amount, 0)) filter (where lower(coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, ''), '')) like '%rajya%' or coalesce(nullif(house, ''), nullif(house_type, ''), nullif(constituency_type, '')) = '1'), 0),
    count(*) filter (where coalesce(risk_score, 0) > 75),
    count(*) filter (where coalesce(risk_score, 0) between 40 and 75),
    count(*) filter (where coalesce(risk_score, 0) < 40)
  from public.projects;
$$;

grant execute on function public.get_public_citizen_breakdown() to anon, authenticated;

-- The proposals table is optional in older installations. When present, make
-- it explicitly public-read and publish it for Supabase Realtime so DPO/CVD
-- changes are visible to the citizen register without a hard refresh.
do $$
begin
  if to_regclass('public.proposals') is not null then
    execute 'alter table public.proposals enable row level security';
    execute 'drop policy if exists "public_read_proposals" on public.proposals';
    execute 'create policy "public_read_proposals" on public.proposals for select to anon, authenticated using (true)';
    execute 'grant select on public.proposals to anon, authenticated';
    begin
      execute 'alter publication supabase_realtime add table public.proposals';
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;
