-- Public citizen transparency feature tables.
-- Run this once in the Supabase SQL Editor before using the citizen actions.

create table if not exists public.citizen_verifications (
  id bigint generated by default as identity primary key,
  project_id text not null,
  work_id text,
  citizen_email text,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  distance_meters numeric(10, 2) not null,
  verified_at timestamptz not null default now()
);

create table if not exists public.citizen_feedback (
  id bigint generated by default as identity primary key,
  project_id text not null,
  work_id text,
  citizen_email text,
  site_status text not null,
  notes text not null,
  evidence_url text,
  forensic_result jsonb,
  flag text default 'Pending Citizen Field Verification',
  created_at timestamptz not null default now()
);

alter table public.citizen_verifications enable row level security;
alter table public.citizen_feedback enable row level security;

drop policy if exists "public_insert_citizen_verifications" on public.citizen_verifications;
create policy "public_insert_citizen_verifications"
  on public.citizen_verifications for insert to anon, authenticated with check (true);

drop policy if exists "public_read_citizen_verifications" on public.citizen_verifications;
create policy "public_read_citizen_verifications"
  on public.citizen_verifications for select to anon, authenticated using (true);

drop policy if exists "public_insert_citizen_feedback" on public.citizen_feedback;
create policy "public_insert_citizen_feedback"
  on public.citizen_feedback for insert to anon, authenticated with check (true);

drop policy if exists "public_read_citizen_feedback" on public.citizen_feedback;
create policy "public_read_citizen_feedback"
  on public.citizen_feedback for select to anon, authenticated using (true);

grant select, insert on public.citizen_verifications to anon, authenticated;
grant select, insert on public.citizen_feedback to anon, authenticated;

-- Evidence bucket. If storage policies are managed separately in your project,
-- keep this insert and add equivalent object INSERT/SELECT policies in Storage.
insert into storage.buckets (id, name, public)
values ('citizen-evidence', 'citizen-evidence', true)
on conflict (id) do nothing;
